/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#d5e3ff",
        "secondary-container": "#dac9ff",
        "on-tertiary": "#ffeef4",
        "on-surface": "#242f41",
        "primary-dim": "#3939c7",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#040e1f",
        "primary-container": "#9396ff",
        "surface-variant": "#cdddfe",
        "error-dim": "#a70138",
        "primary": "#4647d3",
        "on-tertiary-fixed": "#3b002b",
        "secondary-fixed": "#dac9ff",
        "surface": "#f4f6ff",
        "surface-container": "#dee8ff",
        "on-error-container": "#510017",
        "on-primary": "#f4f1ff",
        "on-tertiary-container": "#63054a",
        "surface-dim": "#c3d5f8",
        "on-secondary": "#f8f0ff",
        "tertiary-fixed-dim": "#ef81c4",
        "on-error": "#ffefef",
        "on-secondary-fixed-variant": "#5f28c8",
        "on-surface-variant": "#515c70",
        "primary-fixed-dim": "#8387ff",
        "on-secondary-fixed": "#40009b",
        "surface-container-highest": "#cdddfe",
        "on-tertiary-fixed-variant": "#6e1354",
        "surface-tint": "#4647d3",
        "primary-fixed": "#9396ff",
        "outline-variant": "#a2adc4",
        "surface-bright": "#f4f6ff",
        "on-secondary-container": "#5517bf",
        "outline": "#6c778c",
        "tertiary-fixed": "#ff8ed2",
        "tertiary-dim": "#882a69",
        "tertiary-container": "#ff8ed2",
        "secondary-fixed-dim": "#ceb9ff",
        "on-primary-fixed-variant": "#0e009d",
        "tertiary": "#963776",
        "error-container": "#f74b6d",
        "on-background": "#242f41",
        "surface-container-low": "#ecf1ff",
        "background": "#f4f6ff",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#0a0081",
        "error": "#b41340",
        "inverse-on-surface": "#929db4",
        "secondary-dim": "#5e26c7",
        "secondary": "#6a37d4",
        "inverse-primary": "#8083ff",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
